# Element Web client for the private Matrix server.

services:
  matrix-element:
    image: vectorim/element-web:${MATRIX_ELEMENT_VERSION:-latest}
    container_name: matrix-element
    restart: unless-stopped
    expose:
      - 8080/tcp
    ports:
      - ${MATRIX_ELEMENT_PRIVATE_PORT:-8011}:8080
    environment:
      ELEMENT_WEB_PORT: ${MATRIX_ELEMENT_INTERNAL_PORT:-8080}
    volumes:
      - ../matrix/element/config.json:/app/config.json:ro,Z
