# Open WebUI service.

volumes:
  open_webui_storage:

services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    restart: unless-stopped
    expose:
      - 8080/tcp
    ports:
      - 127.0.0.1:${WEBUI_PRIVATE_PORT:-8080}:8080
    volumes:
      - open_webui_storage:/app/backend/data
